apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai-ticket-intake-prod
resources:
  - ../../base
patches:
  - target:
      kind: Deployment
      name: ai-ticket-intake
    patch: |
      - op: replace
        path: /spec/replicas
        value: 3
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: 200m
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 256Mi
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "1"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 1Gi
images:
  - name: IMAGE_PLACEHOLDER
    newName: image-registry.openshift-image-registry.svc:5000/ai-ticket-intake/ai-ticket-intake
    newTag: stable
